### PR TITLE
move verbose setting parsing to CLI

### PR DESCRIPTION
**Pull request by adamralph**
Relates to #3.

### CODE REVIEW

**Comment by adamralph** [comment]
@bording I did consider that, but I'm not sure it's a good idea equate fat-fingered values like "tru", "ture", "true ", etc .to `false`. I think it's better to surface the problem as early as possible.

**Comment by bording** [comment]
If this was a more critical value, then maybe, but the side effect of setting this is incorrectly is less verbose logging.

**Comment by adamralph** [comment]
That's true, but the user may not realise what they've done and get confused, or even report a bug. It would be swallowing a user's mistake, and I'm not sure that's a good idea.

**Comment by adamralph** [comment]
I've decided against it anyway. The error message goes from this:

> C:\Users\adam\.nuget\packages\minver\1.0.0-alpha.13\build\MinVer.targets(17,5): error MINVER0003: MinVerVerbose/MINVER_VERBOSE value 'foo' cannot be converted to a Boolean value. [C:\code\adamralph\liteguard\src\LiteGuard\LiteGuard.csproj]

to this:

>   Unhandled Exception: McMaster.Extensions.CommandLineUtils.CommandParsingException: Invalid value specified for verbose. Cannot convert 'foo' to a boolean. ---> System.FormatException: Invalid value specified for verbose. Cannot convert 'foo' to a boolean.
>      at McMaster.Extensions.CommandLineUtils.Abstractions.BooleanValueParser.Parse(String argName, String value, CultureInfo culture) in C:\projects\commandlineutils\src\CommandLineUtils\Internal\ValueParsers\BooleanValueParser.cs:line 33
>      at McMaster.Extensions.CommandLineUtils.CommandOption`1.McMaster.Extensions.CommandLineUtils.IInternalCommandParamOfT.Parse(CultureInfo culture) in C:\projects\commandlineutils\src\CommandLineUtils\CommandOption{T}.cs:line 47
>      at McMaster.Extensions.CommandLineUtils.CommandLineApplication.HandleParseResult(ParseResult parseResult) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 548
>      --- End of inner exception stack trace ---
>      at McMaster.Extensions.CommandLineUtils.CommandLineApplication.HandleParseResult(ParseResult parseResult) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 574
>      at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 535
>      at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\projects\commandlineutils\src\CommandLineUtils\CommandLineApplication.cs:line 597
>      at MinVer.Cli.Program.Main(String[] args) in C:\code\adamralph\min-ver\MinVer.Cli\Program.cs:line 51
>  C:\Users\adam\AppData\Local\Temp\min-ver-tests-package\packages\minver\1.0.0-build.0\build\MinVer.targets(15,5): error MSB3073: The command "dotnet "C:\Users\adam\AppData\Local\Temp\min-ver-tests-package\packages\minver\1.0.0-build.0\build\../MinVer/MinVer.Cli.dll" --build-metadata "build.1" --path "C:\Users\adam\AppData\Local\Temp\min-ver-tests-package" --major-minor "" --tag-prefix "v." --verbose "foo"" exited with code -532462766. [C:\Users\adam\AppData\Local\Temp\min-ver-tests-package\min-ver-tests-package.csproj]

**Pull request closed without merging**
