### PR TITLE
overhaul options

### PR DESCRIPTION
**Pull request by adamralph**
relates to #3

### CODE REVIEW

**Comment by bording** [comment]
🤔 I'll need to take a close look at this later, but initial reaction is that this feels like too much and there's likely a simpler way.

**Comment by adamralph** [comment]
Thanks @bording, as usual your opinion would be valued.

**Comment by adamralph** [comment]
BTW the precedence was the wrong way round. I've fixed it in #98.

**Comment by adamralph** [comment]
Superseded by #102.

**Pull request merged**
